[dev]
  command = "npm run dev --prefix client"
  framework = "#custom"

[build]
  base = "/"
  functions = "server/src/"
  publish = "client/dist/"
  command = "npm run build-app"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/server/:splat"
  status = 200